app = 'muse-crm-web'
primary_region = 'nrt'

[build]
  dockerfile = "Dockerfile"

[env]
  NEXT_PUBLIC_API_BASE = "https://muse-crm.fly.dev/api/v1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
